spring.application.name=vital

spring.config.import=optional:file:.env[.properties]


spring.datasource.url=jdbc:sqlserver://localhost:1435;databaseName=emergency_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=EmergencyVital2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

server.port=8080

spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration


spring.flyway.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver